/*
 * go-architecture-sample
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package handler

type InlineObject2 struct {
	UserId int64 `json:"user_id,omitempty"`

	Title string `json:"title,omitempty"`
}

// AssertInlineObject2Required checks if the required fields are not zero-ed
func AssertInlineObject2Required(obj InlineObject2) error {
	return nil
}

// AssertRecurseInlineObject2Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of InlineObject2 (e.g. [][]InlineObject2), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInlineObject2Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInlineObject2, ok := obj.(InlineObject2)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInlineObject2Required(aInlineObject2)
	})
}
